### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [IsmailAlaouiAbdellaoui/Trading-Rules-Generation-Genetic-Algorithm#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by IsmailAlaouiAbdellaoui** [comment]
You are free to use it as much as you like.
However, please bear in mind that it might be exhausting to understand the code as the coding part was not properly planned  (as well as team-based), therefore the structure is sub-optimal to say the least :)
Good luck and don't hesitate if you have further questions ;)
